mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from . import views

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('users/', include('users.urls')),
    path('journal/', include('journal.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('', views.users_main_view, name='user_main'),
    path('register/', views.user_registration_view, name="registration"),
    path('login/', views.user_login_view, name="login"),
    path('logout/', views.user_logout_view, name="logout")

]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms  import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def users_main_view(request):
    return render(request, 'user_main.html')

def user_registration_view(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('journal:journal_list')
        
    else:
        form = UserCreationForm()
    
    return render(request, 'user_registration.html' , {"form":form})


def user_login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            # If you tried to access a protected resource before logging this sends you to that resource after login
            if 'next' in request.POST:
                return redirect (request.POST.get("next")) 
            else:
                return redirect('journal:journal_list')
    else:
        form = AuthenticationForm(request.GET)
    return render(request, 'user_login.html', {"form": form})

        
def user_logout_view(request):
    if request.method =="POST":
        logout(request)
        return redirect('users:user_main')

users/templates/user_login.html
<!--prettier-ignore -->
{%extends 'layout.html' %}

{% block title %}
  User Login
{% endblock %}

{% block content%}
  <section class="container mt-4 text-center">
    <h1>User Login</h1>
  {% comment %} Adding new user form {% endcomment %}
    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group mb-2 text-center">
          <label class="form-text">{{field.label}}</label>
          <div class="d-flex justify-content-center input-group">

            {{field}}
          </div>
        </div>

        {% for error in field.errors%}
          <div class="text-danger">
            {{error}}
          </div>
        {%endfor%}
      {%endfor%}
      {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}" />
      {% endif%}
      <button class="btn btn-primary">Submit</button>
    </form>
  </section>
  <script></script>
{% endblock%}

users/templates/user_main.html
<!--prettier-ignore -->
{%extends 'layout.html' %}

{% block title %}
  Users
{% endblock %}

{% block content%}
  <section class="container text-center mt-4">
    <div class="d-flex flex-column justify-content-center" >


      <h1>You are not currently logged in</h1>
      <p>Please use the options below to either create a user ID or login</p>

      <a class ="btn btn-primary" href="{%url 'users:login' %}">Log In</a>
      <a  class= "btn btn-secondary" href="{%url 'users:registration'%}">Register</a>

    </div>
  </section>

{% endblock%}

users/templates/user_registration.html
<!--prettier-ignore -->
{%extends 'layout.html' %}

{% block title %}
  registration
{% endblock %}

{% block content%}
  <section class="container mt-4 text-center">
    <h1>New User Registration</h1>
  {% comment %} Adding new user form {% endcomment %}


    <form class="mx-auto" style="max-width: 400px" action="{% url 'users:registration'%}" method="post">

      {% csrf_token %}
      {% for field in form%}
        <div class="form-group mb-2 text-center">
          <label class="form-text">{{field.label}}</label>
          <div class="d-flex justify-content-center input-group ">

            {{field}}
          </div>
          {% for error in field.errors%}
            <div class="text-danger">
              {{error}}
            </div>
          {%endfor%}


        </div>
      {%endfor%}

      <button class="btn btn-primary w-100">Submit</button>
    </form>

  </section>
  <script></script>
{% endblock%}