mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from . import views

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('users/', include('users.urls')),
    path('journal/', include('journal.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('', views.users_main_view, name='user_main'),
    path('register/', views.user_registration_view, name="registration"),
    path('login/', views.user_login_view, name="login"),
    path('logout/', views.user_logout_view, name="logout")

]

templates/home.html
<!-- prettier-ignore -->
{% extends 'layout.html' %}
{% block title %}
  Home
{%endblock %}


{% block content %}

  <div class="container text-center mt-5">
    {%if user.is_authenticated %}
      <h1 class="fw-bold">Welcome to your journal {{user}}</h1>
      <p class="text-muted">Write, reflect, and track your thoughts over time.</p>
      <div class="d-flex justify-content-center gap-3 mt-4">
        <a href="/journal" class="btn btn-primary">View my Journals</a>
      </div>
    {% else %}
      <h1 class="fw-bold">Suffer peasant</h1>
    {% endif%}
  </div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static%}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Journaling App</title>
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Home</a>

        {% comment %} Navbar toggler for mobile button thingy {% endcomment %}
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        {% comment %} Navbar Items {% endcomment %}
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav w-100">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="/journal">Journal Listing</a>
              </li>

              <li class="nav-item ms-auto">
                <form
                  class="d-inline"
                  action="{% url 'users:logout' %}"
                  method="post"
                >
                  {% csrf_token %}
                  <button class="btn btn-outline-light">Logout</button>
                </form>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/users">Login</a>
              </li>
            {% endif%}
          </ul>
        </div>
      </div>
    </nav>
    <div>
      <main>{% block content %} {% endblock %}</main>
    </div>
  </body>
</html>