journal/urls.py
from django.urls import path, include
from . import views

app_name= "journal"

urlpatterns = [
    path('',views.journal_list, name='journal_list' ),
    path('new/', views.journal_new, name='journal_new'),
    path('<slug:journal_slug>/', views.journal_book_view, name="journal_book"),
    path('<slug:journal_slug>/edit', views.edit_journal_book_view, name="edit_journal_book"),
    path('<slug:journal_slug>/delete', views.delete_journal_book_view, name="delete_journal_book"),
    # include works when you want to have it look at the URLs from another url file
    # in this case I want a url => journal-x-x-blah/entries/journal-page-blah
    path('<slug:journal_slug>/entries/', include("journal_pages.urls", namespace="journal_pages"))
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from . import views

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('users/', include('users.urls')),
    path('journal/', include('journal.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

urlpatterns = [
    path('', views.users_main_view, name='user_main'),
    path('register/', views.user_registration_view, name="registration"),
    path('login/', views.user_login_view, name="login"),
    path('logout/', views.user_logout_view, name="logout")

]

journal/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User



# Create your models here.

class Journal(models.Model):
    journal_title = models.CharField(max_length=300, help_text="What is the title of the journal book?", unique=True)
    purpose = models.CharField(max_length=300, help_text= "Describe the purpose of this journal")
    journal_type = models.CharField(max_length=50, help_text="What type of journal (weekly, learning, scientific, etc) is this?")
    start_date = models.DateField(auto_now_add=True)
    slug = models.SlugField(blank=True, unique=True)
    banner_image=models.ImageField(upload_to="journal_banners/", default='fallback.png', blank = True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


# Trying to do self.pk or fucking with the dates for some reason returns them as NoneTypes when its saving/retrieving.  I'll just do the normal slugify of the journal title, though can open a problem if there's multiple journal titles that are the same.

    def save(self, *args, **kwargs):
            base_slug = slugify(self.journal_title)
            self.slug = base_slug
            super().save(*args, **kwargs)


   

    def __str__(self):
        return self.journal_title
    

journal/forms.py
from django import forms 
from .import models

# Turns out I can just make the form dynamic and I only really need 1 form
# class CreateJournal(forms.ModelForm):
# #     class Meta:
# #         model = models.Journal
# #         fields = ['journal_title', 'purpose', 'journal_type', 'banner_image']
# #         exclude = ['slug']
# #         widgets = {
# #             'journal_title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Enter the title of your journal book"}),
# #             'purpose': forms.Textarea(attrs={'class': 'form-control', 'rows':4, 'placeholder': 'Describe the purpose of this journal'}),
# #             'journal_type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'What type of journal is this?'}),
# #             'banner_image': forms.FileInput(attrs={'class':'form-control'})
# #         }

# # class EditJournal(forms.ModelForm):
# #     class Meta:
# #         model = models.Journal
# #         fields = ['journal_title', 'purpose', 'journal_type', 'banner_image']
# #         exclude = ['slug']



class JournalForm(forms.ModelForm):
    class Meta:
        model = models.Journal
        fields = ['journal_title', 'purpose', 'journal_type', 'banner_image']
        exclude = ['slug']
        widgets = {
            'journal_title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Enter the title of your journal book"}),
            'purpose': forms.Textarea(attrs={'class': 'form-control', 'rows':4, 'placeholder': 'Describe the purpose of this journal'}),
            'journal_type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'What type of journal is this?'}),
            'banner_image': forms.FileInput(attrs={'class':'form-control'})
        }

journal/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.http import HttpResponse
from .models import Journal
from journal_pages.models import Journal_Entry
from django.contrib.auth.decorators import login_required
from . import forms
import logging

logger = logging.getLogger(__name__)


@login_required(login_url="/users/login/")
def journal_list(request):
    # journals = Journal.objects.all().order_by('-start_date')
    journals = Journal.objects.filter(author = request.user.id)
  
    
    return render(request, 'journal_list.html', {'journals': journals} )


@login_required(login_url="/users/login/")
def journal_new(request):
    if request.method == "POST":
        form = forms.JournalForm(request.POST, request.FILES)
        if form.is_valid():
            new_journal = form.save(commit=False)
            new_journal.author = request.user
            new_journal.save()
            return redirect('journal:journal_list')
            
        else:
            return render(request, 'journal_list.html')
    else:
        form = forms.JournalForm()

   
    return render(request, 'journal_form.html', {'form': form})

@login_required(login_url="/users/login/")
def journal_book_view(request, journal_slug):
    # we grab the specific item we need based on the slug value thats auto generated
    journal = Journal.objects.get(slug = journal_slug)
    
    # This ended up being what I needed to do.  
    # I needed to filter the entries based on journal_book corresponding to the journal
    # it works with journal but I prefer to specify journal.id for my own learning
    journal_entry = Journal_Entry.objects.filter(journal_book=journal.id).order_by('-entry_date')
    return render(request, 'journal_book.html', {'journal': journal , 'journal_entry': journal_entry })

def edit_journal_book_view(request, journal_slug):
    journal = get_object_or_404(Journal, slug=journal_slug )
    if request.method =='POST':
        form = forms.JournalForm(request.POST, request.FILES, instance = journal)
        if form.is_valid():
            form.save()

            editted_journal = get_object_or_404(Journal, id = journal.id)
            return redirect('journal:journal_book', editted_journal.slug)
        
        else:
            print("Form Errors", form.errors)

    else:
        form = forms.JournalForm(instance = journal)

    return render (request, 'journal_form.html', {'journal':journal, 'form':form})


def delete_journal_book_view(request, journal_slug):
    journal = get_object_or_404(Journal, slug=journal_slug )
    if request.method == 'POST':
        journal.delete()
        return redirect('/')
    
    return redirect('/')

journal/templates/journal_book.html
<!--prettier-ignore -->

{% extends 'layout.html' %}
{%block title%}
  {{journal.journal_title}}
{%endblock %}
{% block content %}

  <div class="container mt-4">
    <h1 class="text-center">{{journal.journal_title}}</h1>

    <section class="text-center mb-4">
      <img
        src="{{journal.banner_image.url}}"
        alt="{{journal.journal_title}}"
        class="img-fluid mb-4"
      />
      <h2>Purpose: {{journal.purpose}}</h2>
      <h3>Type of journal: {{journal.journal_type}}</h3>
      <p>Date started: {{journal.start_date}}</p>
    </section>

    <section class="text-center mb-2">
      <h3>Journal Actions</h3>
      <div class="container">
        <div class="d-flex mb-4 row row-cols-2 justify-content-center">
          <button id="edit_button" class="btn btn-secondary">Edit</button>
        {% comment %} I forgot I have the delete view require a post... plus
        yea, we wouldn't want it to delete records by getting them from the
        database lols {%endcomment %}

          <form
            action="{%url 'journal:delete_journal_book' journal.slug %}"
            method="post"
          >
            {% csrf_token %}
            <button
              id="delete_button"
              onclick="return confirm('You are sure you want to delete this journal to include all of its entries, if any ?')"
              class="btn btn-danger w-100"
            >
              Delete
            </button>
          </form>
        </div>
      </div>
      <h3>Journal Entry Actions</h3>
      <button class="btn btn-primary w-100" onclick="createNewEntry()">
        New Entry
      </button>
    </section>

    <section class="row justify-content-center text-center mb-3">
      <h3>Journal Entries</h3>
      {% for entry in journal_entry%}
        <div class="col-md-6 col-lg-3 mb-2">
          <a
            href="{% url 'journal:journal_pages:view_journal_entries' journal.slug entry.slug%}"
          >
            <div class="card h-100 shadow-sm text-center border-1">
              <div class="card-body">
                <h5 class="card-title">{{entry.entry_title}}</h5>
                <p class="card-text">{{entry.entry_date}}</p>
              </div>
            </div>
          </a>
        </div>
      {% empty %}
        <li>There are no journal entries</li>
      {% endfor %}
    </section>
    <script>
    // I wanted to do some javascripty script
      document.getElementById("edit_button").onclick = function () {
        window.location.href =
          "{% url 'journal:edit_journal_book' journal.slug %}";
      };

      let createNewEntry = () =>
      (window.location.href =
        "{% url 'journal:journal_pages:new_journal_entry' journal.slug %}");

    // I've been liking this approach  instead of using form html element.  For future projects I'll start trying to incorporate more javascript.  For a future project there will most likely be a main js file
    </script>
  </div>

{% endblock %}

journal/templates/journal_form.html
<!--prettier-ignore -->
{%extends 'layout.html' %}

{% block title%}
{% comment %} if there is a primary key for the form then its edit mode, otherwise its new mode {% endcomment %}
  {%if form.instancec.pk%} Edit Journal {% else %} New Journal {% endif %}
{% endblock %}

{% block content %}

  <div class="container mt-4">
    <section class="text-center mb-3">
      <h1>{% if form.instance.pk %}
        Edit Journal Book
      {%else %}
        New Journal Registration {% endif %}</h1>
      <div class="row justify-content-center">
        <div class="col-md-6">
{% comment %} Apparently if you leave action="" it submits the post request to the same url form it was loaded from {% endcomment %}
          <form
            action=""
            method="post"
            enctype="multipart/form-data"
          >
            {% csrf_token %}
            {% for field in form %}
              <div class="mb-2">
                <label for="{{field.id_for_label}}" class="visually-hidden">{{field.label}}</label>
                {% if field.name == 'banner_image' %}
                  <label class='form-text'>{{field.label}}</label>
           {% comment %} <input type="file" name="{{field.name}}" id="{{ field.id_for_label }}" class="form-control"> 
           Something with bootstrap and FileINput/ClearableFileInput and it doesn't render the banner_image field unless I manually tell it to render the field.

           Also.. becareful with clearable file input.. now I gotta either flush the DB or add in a {%if banner image} 
           {% endcomment %}
                  {{field}}
                {% endif %}
                {% if field.help_text%}
                  <div class="form-text">{{field.help_text}}</div>
                  {{field}}

                {% endif %}
                {% for error in field.errors %}
                  <div class="text-danger">{{error}}</div>
                {% endfor %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">
              {% if form.instance.pk %}
                Update Journal
              {% else %}
                Submit
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </section>
  </div>

{% endblock%}

{% comment %} Yea turns out by checking for an instance of a primary key you can make the form dynamic to new or edit, eliminating the need for a separate edit/new html file {% endcomment %}

journal/templates/journal_list.html
<!--prettier-ignore -->
{% extends 'layout.html' %}

{%block title%}
  Journal List
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h1 class="text-center mb-3">Your list of Journals</h1>
    <div class="text-center mb-4">
      <h3>If you wish to create a new journal</h3>
      <button onclick="redirect()" class="btn btn-primary">Click Here</button>
    </div>

    {% if journals %}
      <div class="row justify-content-center">
        {% for journal in journals%}
          <div class="col-md-6 col-lg-3 mb-4">
            <a
              href="{% url 'journal:journal_book' journal_slug=journal.slug %}"
              class="text-decoration-none"
            >
              <div
                class="card h-100 shadow-sm text-white text-center border-0"
                style="background: linear-gradient(rgba(0,0,0, 0.5), rgba(0,0,0, 0.5)), url('{{journal.banner_image.url}}') center/cover no-repeat; min-height:200px;"
              >
                <div class="card-img-overlay d-flex flex-column justify-content-end">
                  <h5 class="card-title">
                    {{ forloop.counter }}. {{ journal.journal_title }}
                  </h5>
                  <p class="card-text flex-grow-1">
                    <strong>Type:</strong>
                    {{ journal.journal_type }}
                    <br />
                    <strong>Purpose:</strong>
                    {{ journal.purpose }}
                  </p>
                </div>
              </div>
            </a>
          </div>

        {% endfor %}
      </div>

    {% else %}
      <p class="text-center text-muted">There is nothing here</p>
    {% endif %}
  </div>

  <script>
    let redirect = () =>
    (window.location.href = "{% url 'journal:journal_new' %}");
  </script>
{% endblock %}